apiVersion: v2
name: app-chart
description: A Helm chart for Kubernetes

type: application
version: 0.2.0
appVersion: 1.16.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled