server:
  port: 9000

spring:
  profiles:
    active: prod
  redis:
    host: ${REDIS_URL}
  session:
    store-type: redis
#  security:
#    sessions: NEVER

logging:
  level:
    org:
      springframework:
        security: DEBUG