apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | quote }}
  DB_URL: {{ printf "jdbc:postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | quote }}
