apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: example-redis-config
  files:
  - redis-config
generatorOptions:
  disableNameSuffixHash: true
resources:
- redis-pod.yaml
